services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - ./volumns/redis:/data
    ports:
      - "6379:6379"
    networks:
      - tasker

  postgres_user:
    container_name: postgres_user
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    volumes:
      - ./volumns/postgres-user:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tasker

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./volumns/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tasker

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: true
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.authc.api_key.enabled: true
      xpack.monitoring.collection.enabled: true
      xpack.security.enrollment.enabled: true
      xpack.security.authc.token.enabled: true
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./volumns/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - tasker
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.1
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./config/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - tasker
      - elastic
    depends_on:
      - elasticsearch

networks:
  tasker:
  elastic:
