FROM node:20-alpine3.18

WORKDIR /app

COPY package*.json .npmrc ./
RUN --mount=type=secret,id=npmrc \
    NPM_TOKEN=$(cat /run/secrets/npmrc) \
    npm install
COPY src ./src

EXPOSE 8000

CMD ["npm", "run", "dev"]

# docker image build --secret id=npmrc,src=npmrc -t notification:dev -f backend/2-notification/dockerfile.dev .
