apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  namespace: production
spec:
  storageClassName: postgres-auth-local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
