apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-queue
  template:
    metadata:
      labels:
        app: tasker-queue
    spec:
      containers:
        - name: tasker-queue
          image: rabbitmq:3.13-rc-management-alpine
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: 150Mi
              cpu: 100m
          ports:
            - name: queue
              containerPort: 5672
              protocol: TCP
            - name: mgmt
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbittmq-local-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbittmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
