apiVersion: v1
kind: Service
metadata:
  name: tasker-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: tasker-redis
  ports:
    - name: tasker-redis
      port: 6379
      targetPort: 6379
