apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-deployment-config
  namespace: production
  labels:
    k8s-app: apm-server
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"

      rum:
        enabled: true

      kibana:
        enabled: true
        host: "${KIBANA_HOST}:${KIBANA_PORT}"
        protocol: "http"
        username: "elastic"
        password: "tasker"

    auth:
      secret_token: ""
      anonymous:
        enabled: true

    strict:
      perms: false

    setup.kibana:
      host: "${KIBANA_HOST}:${KIBANA_PORT}"
      template:
        settings:
          index.number_of_replicas: 1

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      enabled: true
      protocol: "http"
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.enabled: false

    monitoring.enabled: true

    monitoring.elasticsearch:
      protocol: "http"
      hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: production
spec:
  type: ClusterIP
  selector:
    k8s-app: apm-server
  ports:
    - name: apm-server
      port: 8200
      targetPort: 8200
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: production
  labels:
    k8s-app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: apm-server
  template:
    metadata:
      labels:
        k8s-app: apm-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:8.12.1
          env:
            - name: ELASTICSEARCH_HOST
              value: tasker-elastic.production.svc.cluster.local
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: tasker
            - name: KIBANA_HOST
              value: tasker-kibana.production.svc.cluster.local
            - name: KIBANA_PORT
              value: "5601"
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: apm-server
              containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: /usr/share/apm-server/apm-server.yml
              readOnly: true
              subPath: apm-server.yml
      volumes:
        - name: config
          configMap:
            name: apm-server-deployment-config
