apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  storageClassName: elasticsearch-local-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
